name: habhoub
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  flutter_svg: ^2.0.7
  file_picker: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo_aibs.svg
    - assets/icons/importer.svg

